version: '3.1'

services:
  mysql:
    image: mysql
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: root
    volumes:
      - ./db/ :/docker-entrypoint-initdb.d/
    

  phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8082:80
      environment:
        - PMA_ARBITRARY=1

  php-7.4:
    image: arthurelinux/php74apache
    ports:
      - 8080:80
    volumes:
      - ./log/apache2:/var/log/apache2
      - ./html:/var/www/html
      
    depends_on:
      - mysql
      - phpmyadmin